import { useEffect, useState } from 'preact/hooks';

interface TOCItem {
  id: string;
  title: string;
}

export default function DynamicToC() {
  const [items, setItems] = useState<TOCItem[]>([]);

  useEffect(() => {
    const scan = () => {
      // 1. Select only the iframes generated by CodeFrame
      const sketches = document.querySelectorAll('iframe[title="Code Preview"]');
      
      const found: TOCItem[] = Array.from(sketches).map((iframe, index) => {
        // 2. Find the top-level container of the whole EditableSketch component
        // 'my-md' is the class used in your CodeEmbed.jsx
        const container = iframe.closest('.my-md') as HTMLElement;
        
        const id = container?.id || `sketch-step-${index}`;
        if (container && !container.id) container.id = id;

        // 3. Find the closest title by looking at previous siblings
        let title = `Sketch ${index + 1}`;
        let sibling = container?.previousElementSibling;

        while (sibling) {
          if (/^H[1-6]$/.test(sibling.tagName)) {
            title = sibling.textContent || title;
            break;
          }
          // Stop if we hit another sketch container to avoid stealing its title
          if (sibling.classList.contains('my-md')) break;
          sibling = sibling.previousElementSibling;
        }

        return { id, title: title.trim() };
      });

      // Update state if the content actually changed
      setItems(prev => {
        const nextJSON = JSON.stringify(found);
        return JSON.stringify(prev) === nextJSON ? prev : found;
      });
    };

    // Run once on mount
    scan();

    // The MutationObserver ensures we catch the moment the 'placeholder'
    // div is replaced by the actual 'CodeEmbed' content.
    const observer = new MutationObserver(() => scan());
    observer.observe(document.body, { childList: true, subtree: true });

    return () => observer.disconnect();
  }, []);

  if (items.length === 0) return null;

  return (
    <nav className="toc-box border-l-4 border-indigo-500 bg-gray-50 p-4 my-6">
      <p className="text-xs font-black uppercase text-gray-400 tracking-tighter mb-3">
        Tutorial Sections
      </p>
      <ul className="space-y-2">
        {items.map((item) => (
          <li key={item.id}>
            <a href={`#${item.id}`} className="text-sm text-indigo-600 hover:underline">
              {item.title}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
}